### ISSUE TITLE
【bug】收集完Vmware信息之后，输出分析数据的结果，在结果里的启动方式那一项全部都显示“efi”

### ISSUE THREAD

**Issue by qingyunliu** [Cloud-Discovery/prophet#10]
输出分析结果的时候，发现所有虚拟机的启动方式的一栏全部显示“efi”，登入Vmware之后，查看显示有些主机的启动方式是“bios”，所以判断这是一个bug。

**Comment by CarltonXu** [comment]
> 输出分析结果的时候，发现所有虚拟机的启动方式的一栏全部显示“efi”，登入Vmware之后，查看显示有些主机的启动方式是“bios”，所以判断这是一个bug。

Already fixed it #12
Please check it again.
