### ISSUE TITLE
when install "stevedore" package，can not find the version of 3.5.0

### ISSUE THREAD

**Issue by qingyunliu** [Cloud-Discovery/prophet#6]
ERROR: No matching distribution found for stevedore==3.5.0 (from -r requirements.txt (line 12)）

**Comment by xiaoquqi** [comment]
Please send more your environment info for us, like python version.

**Comment by qingyunliu** [comment]
刚开始用的是python2.7，安装的时候报错，换成python3之后，就可以成功安装了。谢谢。

**Comment by oneprocloud** [comment]
Update README to use Python3 as default
